version: '3.8'

services:
  tsap-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8021:8021"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./cache:/app/cache
    environment:
      - TSAP_ENV=production
      - TSAP_LOG_LEVEL=INFO
      - TSAP_PERFORMANCE_MODE=standard
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8021/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional service for visualizing logs
  tsap-dashboard:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - tsap-server
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

volumes:
  grafana-storage: